name: CI
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install poetry
          poetry lock
          poetry install
          poetry build
          poetry run pyinstaller ./openrover/pitstop.py --onefile
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}
          path: dist/
