name: CI
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install poetry
          poetry install
          poetry build
          poetry run pyinstaller ./openrover/pitstop.py --onefile --hidden-import='pkg_resources.py2_warn'
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}
          path: dist/
  
  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: ${{ runner.os }}
        path: dist
    - if: runner.os != 'Windows'
      run: chmod +x dist/pitstop
    - run: dist/pitstop --help

  test-src:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: ${{ runner.os }}
        path: dist
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - run: |
        python -m pip install openrover --find-links dist/
        python -m openrover.pitstop --help

  test-rover:
    continue-on-error: true
    runs-on: openrover
    steps:
      - uses: actions/checkout@v2
      - run: tox
